spring:
  application:
    name: gestion-compte-service
    version: 0.1.0
  server:
    port: 8081
  springdoc:
    swagger-ui:
      path: /swagger-ui.html

  #Database configuration
  datasource:
      database: ega #Nom de la base de donn�es
      hostname: localhost #Base de donn�es local
      port: 5432 #Port pour le serveur de base de donn�es
      username: postgres #nom de l'utilisateur d�finit pour la base de donn�es
      password: postgres #Mot de passe d'acc�s � la base de donn�es pour l'utilisateur
      url: jdbc:postgresql://${spring.datasource.hostname}:${spring.datasource.port}/${spring.datasource.database}?useSSL=false&serverTimezone=UTC&useLegacyDatetime=false
      driver-class-name: org.postgresql.Driver
      hikari:
        connection-test-query: "SELECT 1"
        max-lifetime: 1800000
        idle-timeout: 600000
        leak-detection-threshold: 60000
  jpa:
      hibernate:
        ddl-auto: update
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      database: postgresql
      properties:
        hibernate:
          enable_lazy_load_no_trans: true


